dist: xenial
language: node_js
node_js:
  - "node"

script:
  - set -e
  - "$TRAVIS_BUILD_DIR/travis/install_gcloud.sh"
  - npm install -g firebase-tools
  - gulp inject
  - gulp copy_libs

deploy:
# Separate deployments to various places based on branch and push type
## - sandbox bucket on gcs
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_sandbox
    && gsutil cp -r "$TRAVIS_BUILD_DIR/app/* gs://speed.mlab-sandbox.measurementlab.net/"
  on:
    repo: m-lab/mlab-speedtest
    condition: "$TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push"

# production
- provider: script
  skip_cleanup: true
  script: "firebase use mlab-oti && firebase deploy --only hosting:mlab-speedtest --token $FIREBASE_TOKEN"
  on:
    repo: m-lab/mlab-speedtest
    tags: true
